---
output:
  html_document:
    theme: flatly
editor_options: 
  chunk_output_type: console
---
`r gitlink::ribbon_css("https://github.com/ryjohnson09/New_Covid_Cases_USA", text="View on GitHub")`

```{css, echo=FALSE}
.main-container {
    width: 100%;
    max-width: unset;
}

.main {
    max-width: 940px;
    margin-left: auto;
    margin-right: auto;
}

.jumbotron {
  color: white;
  background-image: url("https://source.unsplash.com/w9KEokhajKw/1920x1080");
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
  height: 50vh;
}
```

```{r setup, include=FALSE}
library(dplyr)
library(connectwidgets)
library(connectapi)
library(htmltools)
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

# Set up connection
client <- connectwidgets::connect(
  server  = Sys.getenv("CONNECT_SERVER"),
  api_key = Sys.getenv("CONNECT_API_KEY")
  )

guids <- c("2ba00055-d3ec-4b2e-bb6b-a6f01e361621", #Param Rmd
           "a5b31034-660e-492f-a97a-005c0e88fee7") #Shiny app

covid_content <- content(client = client) %>% 
  filter(guid %in% guids)
```

```{r}
div(
  class = "jumbotron jumbotron-fluid",
  div(
    class = "container",
    h1("Covid-19", class = "display-4"),
    p("New Covid-19 Cases in the USA")
  )
)
```

### New Cases by State/Province (Parameterized Rmd)
```{r card1}
covid_content %>%
  filter(guid == "2ba00055-d3ec-4b2e-bb6b-a6f01e361621") %>% 
  rsc_card()
```

### 7-day rolling average (Shiny App)
```{r card2}
covid_content %>%
  filter(guid == "a5b31034-660e-492f-a97a-005c0e88fee7") %>% 
  rsc_card()
```
